[package]
name = "thunderhead-rocksdb"
version = "0.1.0"
authors = ["Mike Thvedt <mike.thvedt@gmail.com>"]

[dependencies]
thunderhead-store = { path = "../../../lib/store" }
rocksdb = { path = "../../rocksdb-rs" }
