[package]
name = "thunderhead"
version = "0.1.0"
authors = ["Mike Thvedt <mike.thvedt@gmail.com>"]

[dependencies]
env_logger = "0.3"
futures = { git = "https://github.com/alexcrichton/futures-rs" }
futures-minihttp = { git = "https://github.com/alexcrichton/futures-rs" }
futures-tls = { git = "https://github.com/alexcrichton/futures-rs", features = ["force-openssl"] }
openssl = "0.8"
time = "0.1"

